# Generated by Django 5.1.5 on 2025-01-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('caloric_content', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('healthy', 'Healthy'), ('appetizer', 'Appetizers & Snacks'), ('salad', 'Salads'), ('soup', 'Soups'), ('bread', 'Bread'), ('side_dish', 'Side Dishes'), ('drink', 'Drinks'), ('dessert', 'desserts')], max_length=50)),
                ('description', models.TextField()),
                ('steps', models.TextField()),
                ('total_cooking_time', models.PositiveIntegerField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='images_recipes/')),
                ('country', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('ingredients', models.ManyToManyField(related_name='recipes', to='recipe.ingredient')),
            ],
        ),
    ]
