# Generated by Django 5.1.5 on 2025-10-07 12:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("caloric_content", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("dairy", "Dairy Products"),
                            ("meat", "Meat"),
                            ("fish", "Fish"),
                            ("seafood", "Seafood"),
                            ("vegetables", "Vegetables"),
                            ("fruits", "Fruits"),
                            ("mushrooms", "Mushrooms"),
                            ("grains", "Grains"),
                            ("legumes", "Legumes"),
                            ("flour", "Flour"),
                            ("spices_sauces", "Spices and Sauces"),
                            ("sweets", "Sweets"),
                            ("beverages", "Beverages"),
                            ("oils", "Oils"),
                            ("nuts", "Nuts"),
                            ("herbs", "Herbs"),
                            ("condiments", "Condiments"),
                            ("bakery", "Bakery"),
                        ],
                        default="vegetables",
                        max_length=50,
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("healthy", "Healthy"),
                            ("appetizer", "Appetizers & Snacks"),
                            ("salad", "Salads"),
                            ("soup", "Soups"),
                            ("bread", "Bread"),
                            ("side_dish", "Side Dishes"),
                            ("drink", "Drinks"),
                            ("dessert", "desserts"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("steps", models.TextField()),
                ("total_cooking_time", models.PositiveIntegerField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images_recipes/"
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("avg_rating", models.FloatField(default=0)),
                ("number_reviews", models.IntegerField(blank=True, default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ingredients",
                    models.ManyToManyField(
                        related_name="recipes", to="recipe.ingredient"
                    ),
                ),
                (
                    "liked_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_recipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "rating",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="recipe.recipe",
                    ),
                ),
            ],
        ),
    ]
