# Generated by Django 5.1.5 on 2025-06-13 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="liked_users",
            field=models.ManyToManyField(
                blank=True, related_name="liked_recipes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
