# Generated by Django 5.1.5 on 2025-06-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0002_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="like",
            name="like_count",
        ),
        migrations.AddField(
            model_name="recipe",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
