# Generated by Django 5.1.5 on 2025-09-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0002_recipe_liked_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="number_reviews",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
