# Generated by Django 5.1.5 on 2025-09-03 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0003_alter_recipe_number_reviews_alter_recipe_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="date_created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="updated",
            new_name="updated_at",
        ),
        migrations.AddField(
            model_name="ingredient",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ingredient",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
