# Generated by Django 5.1.5 on 2025-01-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_recipe_number_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('dairy', 'Dairy Products'), ('meat', 'Meat'), ('fish', 'Fish'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('grains', 'Grains'), ('legumes', 'Legumes'), ('spices', 'Spices'), ('sweets', 'Sweets'), ('beverages', 'Beverages'), ('oils', 'Oils'), ('nuts', 'Nuts'), ('herbs', 'Herbs'), ('condiments', 'Condiments'), ('bakery', 'Bakery')], default='vegetables', max_length=50),
        ),
    ]
