# Generated by Django 5.1.5 on 2025-02-01 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_ingredient_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='caloric_content',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('dairy', 'Dairy Products'), ('meat', 'Meat'), ('fish', 'Fish'), ('seafood', 'Seafood'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('mushrooms', 'Mushrooms'), ('grains', 'Grains'), ('legumes', 'Legumes'), ('flour', 'Flour'), ('spices_sauces', 'Spices and Sauces'), ('sweets', 'Sweets'), ('beverages', 'Beverages'), ('oils', 'Oils'), ('nuts', 'Nuts'), ('herbs', 'Herbs'), ('condiments', 'Condiments'), ('bakery', 'Bakery')], default='vegetables', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
