# Generated by Django 5.1.5 on 2025-11-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="avg_rating",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="number_reviews",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
